import test from 'node:test';
import assert from 'node:assert/strict';
import '../web/project-management/model.js';
import '../web/project-management/components.js';
const M=globalThis.GLLProjectModel,C=globalThis.GLLProjectComponents;
const items=[{id:'a',number:1,title:'Corrigir orçamento',body:'Erro ao salvar',labels:['type:bug','priority:critical'],fields:{Status:'Homologação','Módulo':'Orçamento'},assignees:['julie'],state:'OPEN',repository:'repo'},{id:'b',number:2,title:'Nova tela',body:'',labels:['type:feature'],fields:{Status:'Backlog'},assignees:[],state:'OPEN',repository:'repo'}];
test('filtros combinados respeitam busca, tipo, prioridade e responsável',()=>{assert.deepEqual(M.filterItems(items,{search:'ORÇAMENTO',type:'Bug',priority:'Crítica',assignee:'julie'}).map(i=>i.id),['a']);assert.equal(M.filterItems(items,{search:'salvar',status:'Backlog'}).length,0);});
test('status e prioridade do Project prevalecem sobre labels antigas',()=>{assert.equal(M.value({...items[0],fields:{Prioridade:'Baixa'}},'priority'),'Baixa');assert.equal(M.groupItems(items,'status').Homologação.length,1);});
test('conteúdo GitHub não injeta HTML e links fora do GitHub não são navegáveis',()=>{assert.equal(C.escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');assert.equal(C.link('javascript:alert(1)','Abrir'),'Abrir');assert.equal(C.link('https://evil.example','Abrir'),'Abrir');assert.match(C.link('https://github.com/a/b','Abrir'),/rel="noopener noreferrer"/);assert.doesNotMatch(C.card({...items[0],title:'<script>x</script>'}),/<script>/);});
test('Kanban mantém alternativa de teclado e todos os estados',()=>{const html=C.card(items[0]);assert.match(html,/draggable="true"/);assert.match(html,/<select data-status=/);for(const status of M.statuses)assert.ok(html.includes(status));});
